name: Dispatcharr
version: "0.11.2"
slug: dispatcharr
description: IPTV & Stream Management
url: https://github.com/Dispatcharr/Dispatcharr
arch:
  - aarch64
  - amd64
  - armv7
ports:
  9500/tcp: 9500
webui: http://[HOST]:[PORT:9500]
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)?
