name: Blinko
version: "1.0.0"
slug: blinko
description: Self-hosted AI-powered note-taking app for quickly capturing and organizing thoughts
url: https://github.com/blinkospace/blinko
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
docker_api: true
hassio_api: true
homeassistant_api: false
host_network: false
privileged:
  - NET_ADMIN
ingress: true
ingress_port: 1111
panel_icon: mdi:note-text
panel_title: Blinko
ports:
  1111/tcp: null
ports_description:
  1111/tcp: Blinko web interface (not needed when using ingress)
webui: "http://[HOST]:[PORT:1111]"
startup: application
boot: auto
map:
  - addon_config:rw
options:
  nextauth_secret: ""
  postgres_password: ""
  postgres_db: "blinko"
  postgres_user: "blinkouser"
  nextauth_url: ""
  base_url: ""
schema:
  nextauth_secret: password
  postgres_password: password
  postgres_db: str
  postgres_user: str
  nextauth_url: str?
  base_url: str?
