version: '3.8'

networks:
  blinko-network:
    driver: bridge

services:
  postgres:
    image: postgres:14
    container_name: blinko-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: __POSTGRES_PASSWORD__
    volumes:
      - /data/blinko/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network

  blinko:
    image: blinkospace/blinko:latest
    container_name: blinko-website
    restart: always
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: __NEXTAUTH_URL__
      NEXT_PUBLIC_BASE_URL: __NEXTAUTH_URL__
      NEXTAUTH_SECRET: __NEXTAUTH_SECRET__
      DATABASE_URL: postgresql://postgres:__POSTGRES_PASSWORD__@postgres:5432/postgres
    volumes:
      - /data/blinko/app:/app/.blinko
    ports:
      - "1111:1111"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1111/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - blinko-network
